services:
  - type: web
    name: evapoweb
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false

